import type { Metadata } from 'next';
import { Inter as FontSans } from 'next/font/google';
import './globals.css';
import { CalendarWrapper } from './contexts/Calendar/CalendarProvider';
import { AddReservationWrapper } from './contexts/AddReservation/AddReservationProvider';
import { AddRoomWrapper } from './contexts/AddRoom/AddRoomProvider';
import { cn } from '@/app/lib/utils';
import { ReactQueryClientProvider } from './components/ReactQueryClientProvider';
const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});
import { ReactQueryDevtools } from '@tanstack/react-query-devtools';
// const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReactQueryClientProvider>
      <html lang="en">
        <body
          className={cn(
            'min-h-screen bg-background font-sans antialiased bg-gray-100',
            fontSans.variable
          )}
        >
          <CalendarWrapper>
            <AddRoomWrapper>
              <AddReservationWrapper>{children}</AddReservationWrapper>
            </AddRoomWrapper>
          </CalendarWrapper>
        </body>
        <ReactQueryDevtools
          buttonPosition="bottom-left"
          initialIsOpen={false}
        />
      </html>
    </ReactQueryClientProvider>
  );
}
