export const initialPriceConfiguration = {
    isReminding: true,
    partialOccupancyPrice: false,
    weekendPrice: false,
    stayDuration: false,
    childPrice: false,
    mealPrice: false,
    localTaxAmount: false,
    bookingRestrictions: false,
    selectedCurrency: 'EUR',
    selectedMinAge: null,
    selectedMaxAge: null,
    addCostToAdult: false,
    localTaxForChild: '',
    minAgeListOpen: null,
    maxAgeListOpen: null,
    ageRanges: [{ minAge: null, maxAge: null }],
    longStay: 0,
    shortStay: 0,
    mealPrices: {
      bb: '',
      hb: '',
      fb: '',
    },
    mealIncluded: {
      bb: false,
      hb: false,
      fb: false,
    },
    focusedField: null,
  };
  